application:
  name: coffeebot-7-app
  project: coffeebot-7-project
  cloud_region: aws/ap-southeast-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: coffee-db-7-db
routers:
- name: main
  routes:
  - application_name: coffeebot-7-app
    paths:
    - /
