application:
  name: coffeebot-4
  project: coffeebot-4
  cloud_region: aws/ap-southeast-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: coffee-db-4
routers:
- name: main
  routes:
  - application_name: coffeebot-4
    paths:
    - /
