application:
  name: coffeebot
  project: coffeebot
  cloud_region: aws/ap-southeast-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: coffee-db
routers:
- name: main
  routes:
  - application_name: coffeebot
    paths:
    - /
