application:
  name: coffeebot-9-app
  project: coffeebot-9-project
  cloud_region: aws/ap-southeast-2
  publicly_accessible: true
databases:
- type: postgresql
  version: "11.5"
  name: coffee-db-9-db
routers:
- name: main
  routes:
  - application_name: coffeebot-9-app
    paths:
    - /
