version: "3"

services:
  db:
    image: postgres:12-alpine
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file: .env
  web:
    build:
      context: .
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - db

